---
test:
  bind: localhost
  port: 4570
  servers: 1
  max_conns: 1024
  max_persistent_conns: 512
  timeout: 30
  pid: tmp/pids/reaktor.pid
  logdir: log

development:
  bind: localhost
  port: 4570
  servers: 1
  max_conns: 1024
  max_persistent_conns: 512
  timeout: 30
  pid: tmp/pids/reaktor.pid
  logdir: log
  greeting: 'Hi we are in the development env'

production:
  bind: 0.0.0.0
  port: 4570
  servers: 1
  max_conns: 1024
  max_persistent_conns: 512
  timeout: 30
  pid: tmp/pids/reaktor.pid
  logdir: log
