#!/usr/bin/env ruby

require 'rack'
require 'reaktor/server'
require 'resque/server'

app = Rack::URLMap.new(
  '/' => Reaktor::Server.new,
  '/resque' => Resque::Server.new
)
Rack::Server.start app: app
